// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA682LFVnV9Afl50a2e-Sbp5bmwzAw93_g',
    appId: '1:423868418332:web:37c07d7dbebc63b69bd2d9',
    messagingSenderId: '423868418332',
    projectId: 'your-own-ai',
    authDomain: 'your-own-ai.firebaseapp.com',
    storageBucket: 'your-own-ai.appspot.com',
    measurementId: 'G-6XVY7M2ZQN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-hhqGzKADClNHnnGvTDBZi1GF_Xh8c2Y',
    appId: '1:423868418332:android:a45a8c967d8552869bd2d9',
    messagingSenderId: '423868418332',
    projectId: 'your-own-ai',
    storageBucket: 'your-own-ai.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWhCt4_oEygtJVo13nrQ6mqjgvlIMWJr0',
    appId: '1:423868418332:ios:55cff8a3735a05489bd2d9',
    messagingSenderId: '423868418332',
    projectId: 'your-own-ai',
    storageBucket: 'your-own-ai.appspot.com',
    iosClientId: '423868418332-a01unrdqdt76mlff27gb4ak1606tsdcf.apps.googleusercontent.com',
    iosBundleId: 'com.example.yourOwnAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWhCt4_oEygtJVo13nrQ6mqjgvlIMWJr0',
    appId: '1:423868418332:ios:55cff8a3735a05489bd2d9',
    messagingSenderId: '423868418332',
    projectId: 'your-own-ai',
    storageBucket: 'your-own-ai.appspot.com',
    iosClientId: '423868418332-a01unrdqdt76mlff27gb4ak1606tsdcf.apps.googleusercontent.com',
    iosBundleId: 'com.example.yourOwnAi',
  );
}
